name: Trigger Webhook on dist push

on:
  push:
    branches: [dist]

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Call deployment webhook
        run: |
          curl -X POST http://124.223.29.125:3000/webhook \
            -H "Content-Type: application/json" \
            -d '{"ref":"refs/heads/dist"}'
